=begin pod :kind("Type") :subkind("class") :category("exception")

=TITLE class X::ControlFlow::Return

=SUBTITLE Error due to calling return outside a routine

    class X::ControlFlow::Return is X::ControlFlow { }

Thrown when a C<return> is called from outside a routine.

    return;
    CATCH { default { put .^name, ': ', .Str } };
    # OUTPUT: «X::ControlFlow::Return: Attempt to return outside of any Routine␤»

=end pod
